package api

const BASE_VALUE=1
const IMMEDIATE_DEATH_VALUE=-9000

const HEALTH_THRESHOLD=45
const LOW_FOOD_VALUE=12
const FOOD_VALUE=8
const KILL_VALUE=4
const DEATH_VALUE=-3
const RECURSION_LIMIT=5

const NEXT_TO_WALL_VALUE=-1
